# Challenge 3

In this challenge we will work on the `Orders.csv` data set in the previous [Subsetting and Descriptive Stats lab](../../lab-subsetting-and-descriptive-stats/your-code/main.ipynb). In your work you will apply the thinking process and workflow we showed you in Challenge 2.

You are serving as a Business Intelligence Analyst at the headquarter of an international fashion goods chain store. Your boss today asked you to do two things for her:

**First, identify two groups of customers from the data set.** The first group is **VIP Customers** whose **aggregated expenses** at your global chain stores are **above the 95th percentile** (aka. 0.95 quantile). The second group is **Preferred Customers** whose **aggregated expenses** are **between the 75th and 95th percentile**.

**Second, identify which country has the most of your VIP customers, and which country has the most of your VIP+Preferred Customers combined.**

# Q1: How to identify VIP & Preferred Customers?

We start by importing all the required libraries:

In [1]:
# import required libraries

import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import matplotlib
%matplotlib inline
%timeit ,  line_profiler, memory_profiler

16.5 ns ± 0.796 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)

Next, import `Orders.csv` from the "subsetting" lab folder into a dataframe variable called `orders`. Print the head of `orders` to overview the data:

In [3]:
# enter your code here
orders = pd.read_csv("Orders.csv")
orders.head()
orders.tail()

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
397919,541904,581587,22613,2011,12,5,12,pack of 20 spaceboy napkins,12,2011-12-09 12:50:00,0.85,12680,France,10.20
397920,541905,581587,22899,2011,12,5,12,children's apron dolly girl,6,2011-12-09 12:50:00,2.10,12680,France,12.60
397921,541906,581587,23254,2011,12,5,12,childrens cutlery dolly girl,4,2011-12-09 12:50:00,4.15,12680,France,16.60
397922,541907,581587,23255,2011,12,5,12,childrens cutlery circus parade,4,2011-12-09 12:50:00,4.15,12680,France,16.60
397923,541908,581587,22138,2011,12,5,12,baking set 9 piece retrospot,3,2011-12-09 12:50:00,4.95,12680,France,14.85

---

"Identify VIP and Preferred Customers" is the non-technical goal of your boss. You need to translate that goal into technical languages that data analysts use:

## How to label customers whose aggregated `amount_spent` is in a given quantile range?

We break down the main problem into several sub problems:

#### Sub Problem 1: How to aggregate the  `amount_spent` for unique customers?

#### Sub Problem 2: How to select customers whose aggregated `amount_spent` is in a given quantile range?

#### Sub Problem 3: How to label selected customers as "VIP" or "Preferred"?

*Note: If you want to break down the main problem in a different way, please feel free to revise the sub problems above.*

Now in the workspace below, tackle each of the sub problems using the iterative problem solving workflow. Insert cells as necessary to write your codes and explain your steps.

### Sub Problem 1: Aggregation amount_spent

In [11]:
# your code here
agr_customers = orders.groupby(['CustomerID'])['amount_spent'].sum()
agr_customers = agr_customers.sort_values(ascending=False)
print ("Number of Costumers:",agr_customers.count())
agr_customers.head()

Number of Costumers: 4339

CustomerID
14646    280206.02
18102    259657.30
17450    194550.79
16446    168472.50
14911    143825.06
Name: amount_spent, dtype: float64

### Sub Problem 2: upper quantile

In [12]:
best = agr_customers.get(agr_customers >= agr_customers.quantile(0.75))
print("Number of Best:",best.count())
best

NUmber of Best: 1085

CustomerID
14646    280206.020
18102    259657.300
17450    194550.790
16446    168472.500
14911    143825.060
12415    124914.530
14156    117379.630
17511     91062.380
16029     81024.840
12346     77183.600
16684     66653.560
14096     65164.790
13694     65039.620
15311     60767.900
13089     58825.830
17949     58510.480
15769     56252.720
15061     54534.140
14298     51527.300
14088     50491.810
15749     44534.300
12931     42055.960
17841     40991.570
15098     39916.500
13798     37153.850
16013     37130.600
16422     34684.400
12748     33719.730
15838     33643.080
17404     31906.820
17389     31833.680
13098     28882.440
14680     28754.110
13081     28337.380
13408     28117.040
17857     26879.040
16333     26626.800
13777     25977.160
12753     21429.390
12744     21279.290
16210     21086.300
17675     20374.280
17381     20275.610
15039     19914.440
12471     19824.050
12731     18895.910
15159     18641.010
12901     17654.540
12678     17628.460
14031     17286.860
17428     17256.850
13767     17220.360
13881     17159.520
16839     16594.350
12921     16587.090
14607     16569.500
15856     16387.570
17677     16363.230
15189     16225.390
14051     15610.390
15513     14758.220
16133     14589.040
14866     14389.900
16705     14034.990
12681     13787.540
12621     13689.670
12540     13400.240
12433     13375.870
15498     13316.400
12477     13219.740
17735     13110.020
16525     13027.450
14258     12669.980
13078     12627.940
12536     12601.830
15640     12515.660
16000     12393.700
17340     12353.290
12682     12288.220
13113     12245.960
14606     12156.650
12557     11990.960
12939     11581.800
15125     11528.480
14194     11349.520
12971     11189.910
14895     11138.710
12409     11072.670
15482     11054.960
17581     11045.040
13319     10845.550
17107     10815.430
13340     10736.480
14769     10674.750
17139     10668.470
16779     10629.720
17865     10526.320
17706     10504.490
15251     10484.990
14062     10464.850
15615     10399.740
15502     10384.930
16180     10254.180
16843     10196.570
12590      9864.260
13001      9818.820
13199      9817.120
15078      9743.110
12709      9736.520
13458      9646.570
14733      9585.910
16523      9418.470
12567      9401.280
14367      9261.520
14667      9241.200
18092      9068.260
13969      9053.940
12451      9035.520
13488      8968.310
13090      8910.820
16033      8816.400
17017      8694.260
17243      8676.850
17306      8631.310
16656      8625.800
14527      8508.820
12683      8476.570
18139      8438.340
15358      8347.200
16558      8338.490
14056      8214.650
14936      8137.020
16672      8134.940
13854      8109.520
14952      8099.490
18109      8052.970
14796      8022.490
12428      7956.460
15290      7943.220
14849      7930.540
12757      7857.100
17811      7837.730
13093      7832.470
12435      7829.890
13629      7792.360
15044      7700.230
15194      7616.530
18172      7561.680
13263      7454.070
12474      7375.790
12980      7374.900
15465      7354.620
17396      7330.800
12583      7281.380
13018      7277.700
18229      7276.900
16923      7247.610
16729      7239.920
16745      7194.300
16873      7123.620
13324      7121.950
13985      7060.130
14961      7044.680
12766      6989.630
12798      6977.040
12989      6924.110
16713      6923.130
13027      6912.000
16187      6911.440
17416      6893.420
12705      6868.290
12476      6816.420
12830      6814.640
15023      6802.760
18055      6784.190
15601      6776.560
16652      6773.970
16532      6748.800
13576      6717.340
16746      6697.660
15249      6688.460
16353      6675.710
17338      6643.930
12626      6620.480
16182      6617.650
15144      6580.440
12472      6572.110
16814      6509.100
12431      6487.450
18223      6484.540
15694      6479.400
13225      6463.840
13102      6424.090
13871      6403.250
12359      6372.580
13668      6363.590
13709      6328.050
15005      6316.570
17315      6292.260
16126      6287.770
14057      6217.960
12357      6207.670
14060      6140.420
13418      6127.430
17509      6115.140
15939      6115.010
14735      6065.690
12637      6021.900
13097      6010.420
13316      5977.730
14101      5976.790
15382      5955.710
14505      5905.640
14415      5900.280
14944      5900.250
13209      5891.610
13534      5870.080
13050      5836.860
12720      5781.730
15218      5756.890
17686      5739.460
13178      5725.470
16553      5719.820
13468      5704.970
14110      5683.150
14049      5681.720
17049      5659.980
17716      5655.990
13004      5655.910
18118      5653.820
14688      5630.870
17757      5605.290
12481      5596.320
12839      5591.420
16767      5580.600
16161      5575.560
12539      5568.350
15805      5528.480
18225      5509.120
16609      5493.460
16985      5464.120
16265      5447.000
18198      5425.560
12490      5417.930
17809      5411.910
16701      5398.300
17719      5396.040
17850      5391.210
16303      5360.630
13269      5346.230
15150      5314.470
17730      5298.480
17061      5232.230
18226      5228.050
12362      5226.230
15046      5213.770
16258      5203.510
13756      5189.520
16191      5180.520
15727      5178.960
17858      5155.660
13599      5153.670
15903      5126.760
13941      5112.960
17602      5102.970
16700      5076.550
14562      5074.770
15301      5070.350
13139      5064.940
12432      5059.320
15719      5045.610
17426      5037.260
14329      5014.840
14755      5010.280
12444      5005.460
15032      4959.100
15547      4954.840
12437      4951.410
12700      4939.990
15786      4932.200
14709      4921.040
17133      4892.240
12664      4881.880
12688      4873.810
14292      4871.930
17652      4867.720
15738      4812.420
13013      4810.940
15555      4805.170
17365      4801.560
15298      4799.900
15187      4777.180
17690      4757.950
12955      4757.160
14180      4748.520
15152      4745.690
16722      4730.810
12714      4708.860
14159      4693.010
14135      4690.310
14191      4684.760
15291      4668.300
14189      4654.080
14390      4652.820
14286      4628.750
16931      4604.220
13802      4599.420
15093      4597.020
14004      4582.640
17613      4559.150
17068      4552.140
12484      4541.720
13267      4521.490
15299      4507.010
17975      4488.810
12524      4485.720
14426      4481.670
16984      4481.350
17364      4481.180
12627      4478.530
14085      4448.540
14534      4447.050
13069      4436.120
15955      4416.260
16626      4413.100
15874      4405.880
12712      4396.130
13505      4393.630
12752      4366.780
16945      4345.500
14016      4341.210
14800      4339.740
14525      4332.200
17567      4331.480
18251      4314.720
12347      4310.000
15034      4308.610
17937      4301.220
14422      4263.640
12500      4257.820
17419      4226.570
14277      4216.200
15804      4206.390
17920      4204.100
15971      4199.850
12747      4196.010
14146      4191.000
18041      4183.390
12949      4167.220
15570      4165.520
16549      4154.640
13384      4151.930
13555      4149.280
13988      4147.960
15514      4139.460
12569      4124.690
16592      4113.680
17940      4106.440
17377      4100.920
16401      4098.320
16670      4095.900
12749      4090.880
14092      4076.910
12449      4067.290
18087      4055.720
14401      4051.480
12656      4051.170
12867      4036.820
13815      4027.360
12841      4022.350
12957      4017.540
12378      4008.620
14547      4007.540
16186      4006.940
17769      3997.980
15529      3995.230
17001      3989.570
15416      3984.320
17611      3984.220
12779      3981.360
12727      3980.700
14299      3965.620
13523      3964.880
13183      3957.780
17651      3945.000
12473      3938.550
17593      3927.340
14739      3902.280
13999      3901.810
14291      3883.250
18073      3877.520
13124      3866.330
15195      3861.000
16717      3858.380
12662      3849.780
16327      3844.220
13266      3834.260
17091      3827.760
15867      3812.640
12755      3811.950
12597      3811.220
13435      3809.890
12668      3807.150
16145      3799.490
16655      3794.520
16168      3787.600
16019      3786.240
12562      3781.740
17173      3766.600
16904      3754.270
12429      3750.400
17238      3744.650
14145      3742.200
13552      3740.070
16570      3738.400
15808      3734.970
14282      3729.340
12502      3723.870
12647      3722.820
13680      3722.420
16240      3718.800
14364      3717.350
15845      3711.770
15622      3709.560
13148      3707.120
17819      3704.870
15379      3703.290
12553      3692.280
16253      3683.860
15581      3679.970
15296      3672.860
18079      3651.970
13137      3650.410
12417      3649.100
16712      3645.430
13426      3641.320
12619      3641.240
16440      3640.670
13381      3639.310
17230      3638.410
14543      3630.330
17528      3628.500
13327      3627.770
13520      3624.350
17576      3622.680
14040      3614.920
13082      3613.630
15505      3610.960
15113      3609.330
16242      3603.210
15484      3594.310
14132      3586.030
17203      3563.850
17491      3558.870
15544      3546.710
12370      3545.690
14503      3543.260
13448      3539.370
13334      3536.820
12454      3528.340
17160      3518.030
13953      3515.680
16360      3512.530
14395      3507.710
16131      3506.540
14907      3501.100
16458      3482.740
13993      3466.360
13014      3466.280
17758      3456.700
15410      3450.840
13536      3448.290
15129      3447.400
15974      3442.150
17725      3439.080
15676      3435.760
14221      3432.800
12406      3415.300
15981      3408.480
13437      3408.060
17669      3406.720
13198      3401.240
15228      3386.710
13842      3385.620
15708      3364.240
16011      3362.710
14227      3350.960
16818      3349.570
16607      3347.710
17183      3347.310
13015      3346.280
12643      3344.640
12613      3344.380
12594      3338.220
16556      3313.790
13373      3312.250
14841      3295.760
14702      3292.140
15632      3285.310
12480      3281.630
15764      3279.970
17723      3276.400
13952      3251.071
13047      3237.540
15443      3236.910
17050      3228.840
14175      3222.300
13880      3219.770
13268      3214.690
14388      3212.840
16107      3204.160
17220      3198.250
13868      3192.540
17685      3191.530
13758      3190.550
14844      3189.810
12456      3181.040
17672      3178.170
17231      3174.320
16837      3170.980
16041      3166.400
15861      3165.360
17863      3160.000
15065      3158.130
14235      3144.860
13742      3131.020
16156      3122.040
13685      3119.440
16326      3110.960
16678      3109.990
13869      3104.950
14099      3104.170
16905      3102.430
15491      3100.090
14257      3099.720
14565      3099.120
13135      3096.000
17059      3095.040
13362      3090.740
15998      3089.970
16218      3084.680
18272      3078.580
12910      3075.040
13631      3070.420
16686      3062.830
14456      3062.400
17799      3055.930
16940      3049.880
16393      3046.210
16709      3029.870
12598      3023.080
12395      3018.630
18094      3017.300
12754      3010.740
12916      3006.150
15521      3000.200
17659      2999.460
17504      2997.030
12670      2996.050
14307      2995.720
15687      2993.100
14639      2984.490
13451      2976.150
14032      2975.590
15854      2974.650
16497      2965.690
17924      2962.500
14868      2953.590
17084      2949.750
17444      2940.040
16316      2938.910
14530      2925.910
17512      2924.990
15606      2920.160
12906      2919.810
14112      2915.150
12438      2906.850
17644      2895.640
18144      2888.750
12408      2888.550
13735      2885.240
16633      2883.100
15673      2881.020
14251      2879.700
17728      2876.010
14005      2874.720
15628      2870.240
14711      2868.800
13901      2867.200
14535      2864.190
12685      2863.080
18145      2861.550
16928      2847.600
15984      2837.670
14852      2836.690
14572      2832.840
17596      2827.930
14842      2824.690
13174      2817.030
16871      2812.340
12356      2811.430
14903      2810.630
18230      2810.200
13230      2806.970
16081      2806.900
16764      2799.250
15993      2797.570
13769      2796.510
12578      2794.510
12758      2791.590
17739      2791.350
14626      2791.270
17213      2781.230
12388      2780.660
14121      2780.150
17838      2779.300
13870      2770.940
15356      2766.500
15114      2760.560
14854      2759.830
13971      2758.260
15321      2748.310
12669      2744.030
14808      2741.170
14125      2740.430
15696      2736.460
16938      2736.380
16003      2735.370
12840      2726.770
12380      2724.810
12708      2712.910
15796      2711.560
17069      2709.700
13285      2709.120
13654      2707.330
14107      2703.230
14732      2702.490
18097      2697.800
17386      2686.420
12625      2683.820
17346      2676.560
13883      2674.480
14713      2666.360
12360      2662.060
14439      2661.240
15671      2657.130
12721      2656.130
13851      2651.460
16618      2647.590
18260      2643.200
13658      2639.170
17655      2638.940
15752      2637.380
13804      2635.790
13771      2634.450
12520      2634.260
17402      2633.850
18077      2633.010
13422      2626.300
13644      2624.260
17965      2622.570
18210      2621.380
16255      2619.910
14262      2618.230
13021      2616.380
15782      2614.740
14397      2612.960
12836      2612.860
18075      2611.750
12726      2609.100
16241      2607.870
13136      2607.610
14408      2606.530
13983      2603.430
17317      2600.340
12600      2599.040
16919      2596.450
13895      2593.070
14243      2588.770
15033      2586.670
13911      2580.910
14546      2578.090
16912      2575.380
15485      2575.000
18245      2567.060
16308      2560.000
15572      2552.860
14334      2552.210
14701      2549.370
14676      2548.240
13344      2543.720
14776      2538.300
17700      2534.640
13471      2531.580
14659      2529.930
17314      2527.920
13975      2526.280
17449      2520.860
13394      2520.020
15245      2515.840
15271      2507.070
12352      2506.040
13695      2504.130
12517      2502.840
15932      2495.870
16477      2494.460
12483      2484.980
12913      2483.630
16710      2483.040
14315      2481.130
13507      2479.160
13588      2478.950
17682      2474.330
17188      2474.230
14766      2473.370
14502      2470.670
17164      2467.350
12455      2466.860
15750      2465.480
17131      2463.170
13784      2462.790
15674      2446.600
14163      2445.910
15527      2429.780
17071      2429.030
13949      2427.320
16143      2424.940
17722      2424.040
15089      2420.840
15373      2415.910
12397      2409.900
17589      2404.170
15980      2398.860
18065      2392.830
13141      2388.750
15370      2386.050
17530      2385.000
14493      2383.240
14554      2381.040
14239      2380.850
15270      2379.490
13722      2375.410
17434      2373.820
14930      2372.860
13908      2369.550
15755      2364.250
12457      2363.230
17634      2361.970
14030      2360.090
14440      2357.680
15140      2354.250
14309      2352.530
12704      2340.840
18259      2338.600
12584      2338.150
18257      2337.630
17954      2332.720
15281      2332.150
12782      2330.920
15785      2328.970
17313      2328.840
17744      2322.400
17211      2317.220
14290      2314.650
15365      2314.320
13994      2313.140
13704      2308.060
15288      2306.520
16735      2300.560
16550      2298.970
15105      2298.930
13115      2294.780
15704      2293.620
12615      2291.190
13527      2287.510
17696      2285.710
12684      2283.630
16782      2279.900
13317      2273.680
17768      2273.180
14466      2272.400
13700      2265.120
16057      2263.120
16209      2262.620
14432      2255.510
16293      2248.990
17442      2248.560
15235      2247.510
16771      2246.810
15665      2242.010
14211      2241.100
16743      2238.090
14560      2237.770
14700      2235.300
16076      2234.730
15834      2233.750
18242      2232.490
14226      2232.190
14825      2226.910
17591      2225.970
12783      2225.910
13365      2225.370
15722      2222.560
15811      2218.620
12876      2218.020
12653      2209.850
13862      2209.360
15797      2207.400
15179      2206.950
13831      2202.990
17406      2200.420
15123      2199.310
16628      2188.050
15394      2183.540
14341      2182.280
12856      2179.930
12909      2178.670
12501      2169.390
12633      2163.980
13755      2161.350
12935      2160.700
16456      2158.370
14407      2157.730
16379      2157.400
13224      2155.950
16966      2154.970
17272      2148.630
14828      2139.760
12560      2134.010
17400      2129.960
13517      2128.420
14360      2128.230
16407      2126.930
14640      2125.080
15058      2124.990
13632      2121.270
18061      2119.410
18008      2116.190
14691      2114.330
13265      2107.660
18173      2106.840
18093      2106.520
14461      2103.060
14515      2102.090
17861      2100.800
15815      2100.600
13126      2099.640
12610      2099.540
16875      2095.530
17191      2095.130
18283      2094.880
14306      2093.320
13571      2092.320
17490      2092.320
13297      2089.850
18044      2088.600
14810      2087.880
16954      2085.080
18231      2083.270
14696      2078.950
14209      2073.430
18241      2073.090
18219      2069.770
14482      2068.150
12948      2064.950
12928      2062.700
16281      2062.060
14409      2059.450
12518      2056.890
17667      2055.510
14188      2054.360
16150      2053.020
17086      2050.080
17612      2048.450
14232      2048.070
17625      2047.000
13495      2044.870
17597      2044.370
17090      2043.950
13450      2043.720
14001      2043.080
12585      2040.100
13593      2037.080
18069      2036.670
17846      2033.100
13630      2031.780
16409      2028.880
17337      2027.870
16358      2027.500
14544      2024.450
15341      2020.520
14506      2012.170
15531      2007.440
15372      2007.400
16098      2005.630
14730      2005.060
14217      2004.980
14462      2004.020
17082      2003.850
16754      2002.400
15493      2001.800
18188      2001.040
13305      2000.860
16698      1998.000
17827      1995.460
18204      1993.700
17679      1992.110
17088      1991.010
13246      1987.300
13590      1981.920
13725      1980.560
17422      1979.370
16341      1971.870
17997      1970.670
12674      1970.600
17790      1965.550
17218      1960.720
15351      1960.110
14498      1957.320
12853      1957.100
17554      1952.450
14533      1949.720
14653      1947.550
15814      1945.330
15518      1942.450
14418      1937.250
14472      1936.840
15864      1936.320
15157      1936.070
12528      1933.480
14655      1932.230
14978      1931.420
16983      1931.250
13094      1927.320
16942      1920.590
15021      1914.820
17368      1912.670
14285      1910.010
16426      1908.250
17228      1906.090
14210      1905.840
15819      1905.450
14250      1904.050
12762      1898.520
17463      1896.410
17870      1894.350
14934      1890.940
12371      1887.960
15641      1887.200
16170      1885.050
13890      1883.810
16128      1880.220
17738      1879.050
15367      1877.590
17293      1875.110
16986      1873.200
13982      1871.810
16474      1871.500
17469      1870.970
16841      1869.820
14524      1867.680
17787      1865.190
16201      1863.470
14887      1862.000
12423      1859.310
17873      1859.160
14305      1858.960
12963      1856.630
16979      1852.000
13421      1851.080
12383      1850.560
12381      1845.310
17519      1844.020
18180      1843.750
12950      1843.000
17015      1842.560
16102      1842.140
16455      1841.180
14113      1840.420
14216      1839.300
13924      1838.850
14459      1837.920
18287      1837.280
13650      1836.340
15827      1836.090
13048      1835.910
14665      1835.700
16152      1829.040
15203      1827.800
18122      1826.210
17702      1824.370
16153      1824.230
17705      1823.520
16169      1822.970
17828      1820.090
17629      1814.120
15260      1810.770
13481      1804.560
17663      1802.910

### Sub Problem 3: tag customers

In [28]:
tags=['low','medium','prefered','VIP']

orders['BinCustomer'] = pd.qcut(orders['amount_spent'].rank(method='first').values, 4,labels=tags)

orders.head()

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,BinCustomer
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,prefered
1,1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,VIP
2,2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,VIP
3,3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,VIP
4,4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,VIP

Now we'll leave it to you to solve Q2 & Q3, which you can leverage from your solution for Q1:

# Q2: How to identify which country has the most VIP Customers?

# Q3: How to identify which country has the most VIP+Preferred Customers combined?

Provide your solution for Q2 below:

# Q2

In [42]:
# your code here

vips = orders.get(orders['BinCustomer']=='VIP')

vips_country = vips.groupby(['BinCustomer','Country'])['CustomerID'].agg('count')
vips_country.sort_values(ascending=False)

BinCustomer  Country
VIP          United Kingdom          80891
             Germany                  3386
             France                   3119
             EIRE                     3016
             Netherlands              1940
             Switzerland               865
             Australia                 855
             Belgium                   704
             Spain                     673
             Norway                    546
             Portugal                  492
             Channel Islands           331
             Finland                   322
             Italy                     308
             Sweden                    282
             Japan                     241
             Denmark                   231
             Cyprus                    212
             Singapore                 155
             Austria                   144
             Poland                    132
             Israel                    121
             Iceland                    75
             USA                        66
             Greece                     51
             Canada                     50
             Unspecified                44
             United Arab Emirates       42
             Malta                      38
             Lithuania                  27
             Lebanon                    27
             European Community         24
             Czech Republic             20
             RSA                        20
             Brazil                     16
             Bahrain                    12
             Saudi Arabia                3
Name: CustomerID, dtype: int64

# Q3

In [45]:
vips_pref = orders.get((orders['BinCustomer']=='VIP') | (orders['BinCustomer']=='prefered'))
vips_pref.head()
vips_pref.tail()

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,BinCustomer
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30,prefered
1,1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,VIP
2,2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00,VIP
3,3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,VIP
4,4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34,VIP

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,BinCustomer
397918,541903,581587,23256,2011,12,5,12,childrens cutlery spaceboy,4,2011-12-09 12:50:00,4.15,12680,France,16.60,prefered
397920,541905,581587,22899,2011,12,5,12,children's apron dolly girl,6,2011-12-09 12:50:00,2.10,12680,France,12.60,prefered
397921,541906,581587,23254,2011,12,5,12,childrens cutlery dolly girl,4,2011-12-09 12:50:00,4.15,12680,France,16.60,prefered
397922,541907,581587,23255,2011,12,5,12,childrens cutlery circus parade,4,2011-12-09 12:50:00,4.15,12680,France,16.60,prefered
397923,541908,581587,22138,2011,12,5,12,baking set 9 piece retrospot,3,2011-12-09 12:50:00,4.95,12680,France,14.85,prefered

In [46]:
vips_p_country = vips_pref.groupby(['Country'])['CustomerID'].agg('count')
vips_p_country.sort_values(ascending=False)

Country
United Kingdom          164491
Germany                   7061
France                    6289
EIRE                      5938
Netherlands               2105
Spain                     1648
Belgium                   1615
Switzerland               1497
Australia                 1072
Portugal                  1010
Norway                     938
Channel Islands            667
Italy                      659
Finland                    567
Cyprus                     431
Sweden                     392
Austria                    319
Denmark                    312
Poland                     284
Japan                      257
Singapore                  204
Israel                     176
Iceland                    160
USA                        138
Greece                     118
Canada                     111
Malta                       94
Unspecified                 90
United Arab Emirates        56
European Community          56
RSA                         49
Lebanon                     44
Lithuania                   35
Brazil                      32
Czech Republic              24
Bahrain                     16
Saudi Arabia                 7
Name: CustomerID, dtype: int64